### ISSUE TITLE
Weird non-open-source clause in the README... ;)

### ISSUE THREAD

**Issue by justinclift** [deepsidhu1313/javafx-splitpane-ui-sample#1]
Just noticed this in the README:

```
This code is open source use it for non-commercial purpose only.
```

If you're meaning it as a license condition, then the "use it for non-commercial purpose only" bit makes this not open source.  Just so you know. :wink:

**Comment by deepsidhu1313** [comment]
LOL, I don't know that much about Licensing. This examples are for students at my university. Other than that, Anybody who want to learn JAVA or JAVAFX can use these examples. But for commercial purpose the use of these examples is not allowed.

**Comment by justinclift** [comment]
No worries, that's pretty clear. :smile:

**Comment by deepsidhu1313** [comment]
Thanks for raising  the issue. :smiley:
